apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secrets
  namespace: chat-app
type: Opaque
data:
  jwt: NDlPenBSaGlQZzdydFNpSFRMckI5b2ZZMTJRMDdVRURZSW9zeUQ1c2svTFBjKzM0YUhiTXZheDNvcDRlYXZhMg==

